### ISSUE TITLE
Any pre-built files I can use for browsers?

### ISSUE THREAD

**Issue by apple502j** [ultraq/icu-message-formatter#12]
Are there any pre-built files for use in browsers?

**Comment by ultraq** [comment]
None right now, but it shouldn't be too hard to add a built to target browsers.  Will add it as an enhancement for the next version.

**Comment by ultraq** [comment]
OK, 0.11.0 is now up which includes a browser bundle in `/dist/icu-message-formatter.min.js` of the module published to NPM, so you can find it on the unpkg CDN at: https://unpkg.com/@ultraq/icu-message-formatter@0.11.0/dist/icu-message-formatter.min.js

Tried it out on codepen and it seems to be working for the example in the readme anyway: https://codepen.io/ultraq/pen/ZELPNGV?editors=1010

**Comment by apple502j** [comment]
Hmm, is it possible to have a web-compatible ESM version as well?

**Comment by apple502j** [comment]
@ultraq pinging just in case

**Comment by ultraq** [comment]
Ah, yep can add one for that too 👍

**Comment by ultraq** [comment]
0.11.1 is up with an ES module bundle.  I tried again with the same codepen, but this time had this at the top and it seems to work the same:

```javascript
import {MessageFormatter} from 'https://unpkg.com/@ultraq/icu-message-formatter@0.11.1/dist/icu-message-formatter.es.min.js';
```
