### ISSUE TITLE
compiled formatting functions

### ISSUE THREAD

**Issue by ray007** [ultraq/icu-message-formatter#2]
It would be nice to compile the formatting functions once instead of interpret them every time on use.
I've already got a `compile` method for `MessageFormatter`, just tell me if you want pull-requests, or if you want me to spin off my own fork to use.
Next on plan after `compile` for type handler will be correct handling of `'` in messages...

**Comment by ultraq** [comment]
Hey there, storing the results of previous formattings is a pretty good idea.  I'll try a different approach than the compilation method however: I think the `format` function is a good candidate for memoization, and I've already got a memoization function over in another module (https://github.com/ultraq/function-utils#memoizefunc) that can be used here.

If it sounds like memoization won't work with your goals, then feel free to carry on the compilation work in your fork 👍
